import React from 'react';
import {
  X,
  Download,
  User,
  Mail,
  Phone,
  MapPin,
  Calendar,
} from 'lucide-react';

export default function TraineeModal({ trainee, onClose }) {
  const exportProfile = () => {
    const profileContent = `
STC TRAINING MANAGEMENT SYSTEM
SUPERVISORS TRAINING CENTRE - NORTHERN RAILWAY

COMPLETE TRAINEE PROFILE

BASIC INFORMATION
Name: ${trainee.fullName}
Father's Name: ${trainee.fatherName}
Mother's Name: ${trainee.motherName}
Date of Birth: ${new Date(trainee.dateOfBirth).toLocaleDateString()}
Category: ${trainee.category}
Blood Group: ${trainee.bloodGroup}
Marital Status: ${trainee.maritalStatus}
Nationality: ${trainee.nationality}

EMPLOYMENT DETAILS
Employee Name: ${trainee.employeeName}
PF/NPS/UPS No.: ${trainee.pfNumber}
Date of Appointment: ${new Date(trainee.dateOfAppointment).toLocaleDateString()}
Date of Sparing: ${new Date(trainee.dateOfSparing).toLocaleDateString()}
Mode of Appointment: ${trainee.modeOfAppointment}

COURSE INFORMATION
Trainee ID: ${trainee.id}
Ticket Number: ${trainee.ticketNumber}
Batch: ${trainee.batch}
Designation: ${trainee.courseCategory}
Module Number: ${trainee.courseName}
Course Duration: ${trainee.courseDuration}
Stream: ${trainee.stream}

WORK INFORMATION
Unit: ${trainee.unit}
Working Under: ${trainee.workingUnder}
Station Code: ${trainee.stationCode}

CONTACT INFORMATION
Phone: ${trainee.phoneNumber}
Email: ${trainee.email}
Address: ${trainee.address}

EDUCATION
Class 10 Percentage: ${trainee.class10Marks}%
Class 12 Percentage: ${trainee.class12Marks}%
Degree Type: ${trainee.degreeType}
Degree Name: ${trainee.degreeName}
Graduation/PG Marks: ${trainee.graduationMarks}%


${trainee.marks ? `
ACADEMIC PERFORMANCE
Total Marks: ${trainee.totalMarks}/1100
Percentage: ${((trainee.totalMarks || 0) / 1100 * 100).toFixed(2)}%
Grade: ${trainee.grade}
Result: ${((trainee.totalMarks || 0) / 1100 * 100) >= 50 ? 'PASS' : 'FAIL'}

SUBJECT-WISE MARKS:
Railway Organization & Management: ${trainee.marks.railwayOrganization}/100
Role of Mechanical Department: ${trainee.marks.mechanicalDepartmentRole}/100
Rolling Stock Theory – Carriage: ${trainee.marks.rollingStockCarriage}/100
Rolling Stock Theory – Wagon: ${trainee.marks.rollingStockWagon}/100
Rolling Stock Theory – Diesel Loco: ${trainee.marks.rollingStockDiesel}/100
Industrial Safety: ${trainee.marks.industrialSafety}/100
Coach Production Unit: ${trainee.marks.coachProduction}/100
RWF: ${trainee.marks.rwf}/100
DEMU/SPART Manufacturing: ${trainee.marks.demuSpart}/100
Diesel Production Units: ${trainee.marks.dieselProduction}/100
RDSO: ${trainee.marks.rdso}/100
` : 'ACADEMIC PERFORMANCE: Not Available'}

Registration Date: ${new Date(trainee.createdAt).toLocaleDateString()}
Generated on: ${new Date().toLocaleDateString()}
Generated by: STC Training Management System
Supervisors Training Centre - Northern Railway
    `;

    const blob = new Blob([profileContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `complete_profile_${trainee.id}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-6 border-b border-gray-200 sticky top-0 bg-white">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">Complete Trainee Profile</h2>
            <p className="text-sm text-gray-600">{trainee.fullName} - {trainee.id}</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={exportProfile}
              className="px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 text-sm"
            >
              <Download className="h-4 w-4" />
              Export Profile
            </button>
            <button
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="p-6 space-y-8">
          <div className="flex items-start gap-6">
            <div className="w-32 h-40 bg-gray-100 rounded-lg flex items-center justify-center overflow-hidden">
              {trainee.photo ? (
                <img src={trainee.photo} alt="Trainee" className="w-full h-full object-cover rounded-lg" />
              ) : (
                <User className="h-16 w-16 text-gray-400" />
              )}
            </div>
            <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <h3 className="font-semibold text-gray-900 text-lg">{trainee.fullName}</h3>
                <p className="text-gray-600">{trainee.designation} - {trainee.moduleNumber}</p>
                <p className="text-sm text-gray-500">{trainee.id}</p>
                <p className="text-sm text-gray-500">Ticket: {trainee.ticketNumber}</p>
              </div>
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-sm">
                  <Mail className="h-4 w-4 text-gray-400" />
                  <span>{trainee.email}</span>
                </div>
                <div className="flex items-center gap-2 text-sm">
                  <Phone className="h-4 w-4 text-gray-400" />
                  <span>{trainee.phoneNumber}</span>
                </div>
                <div className="flex items-center gap-2 text-sm">
                  <MapPin className="h-4 w-4 text-gray-400" />
                  <span>{trainee.unit} - {trainee.stationCode}</span>
                </div>
                <div className="flex items-center gap-2 text-sm">
                  <Calendar className="h-4 w-4 text-gray-400" />
                  <span>Joined: {new Date(trainee.createdAt).toLocaleDateString()}</span>
                </div>
              </div>
            </div>
          </div>
          {/* Personal Information */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Personal Information</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-700">Father's Name</p>
                <p className="text-gray-900">{trainee.fatherName}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Mother's Name</p>
                <p className="text-gray-900">{trainee.motherName}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Date of Birth</p>
                <p className="text-gray-900">{new Date(trainee.dateOfBirth).toLocaleDateString()}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Category</p>
                <p className="text-gray-900">{trainee.category}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Blood Group</p>
                <p className="text-gray-900">{trainee.bloodGroup}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Marital Status</p>
                <p className="text-gray-900">{trainee.maritalStatus}</p>
              </div>
            </div>
          </div>

          {/* Employment Details */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Employment Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-700">Employee Name</p>
                <p className="text-gray-900">{trainee.employeeName}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">PF/NPS/UPS No.</p>
                <p className="text-gray-900">{trainee.pfNumber}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Date of Appointment</p>
                <p className="text-gray-900">{new Date(trainee.dateOfAppointment).toLocaleDateString()}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Date of Sparing</p>
                <p className="text-gray-900">{new Date(trainee.dateOfSparing).toLocaleDateString()}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Mode of Appointment</p>
                <p className="text-gray-900">{trainee.modeOfAppointment}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Working Under</p>
                <p className="text-gray-900">{trainee.workingUnder}</p>
              </div>
            </div>
          </div>

          {/* Course Information */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Course Information</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-700">Batch</p>
                <p className="text-gray-900">{trainee.batch}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Course Category</p>
                <p className="text-gray-900">{trainee.courseCategory}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Course Duration</p>
                <p className="text-gray-900">{trainee.courseDuration}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Course Name</p>
                <p className="text-gray-900">{trainee.courseName}</p>
              </div>
             <div>
  <p className="text-sm font-medium text-gray-700">Class 10 Percentage</p>
  <p className="text-gray-900">{trainee.class10Marks}%</p>
</div>
<div>
  <p className="text-sm font-medium text-gray-700">Class 12 Percentage</p>
  <p className="text-gray-900">{trainee.class12Marks}%</p>
</div>
<div>
  <p className="text-sm font-medium text-gray-700">Degree Type</p>
  <p className="text-gray-900">{trainee.degreeType}</p>
</div>
<div>
  <p className="text-sm font-medium text-gray-700">Degree Name</p>
  <p className="text-gray-900">{trainee.degreeName}</p>
</div>
<div>
  <p className="text-sm font-medium text-gray-700">Graduation/PG Marks</p>
  <p className="text-gray-900">{trainee.graduationMarks}%</p>
</div>

            </div>
          </div>

          {/* Academic Performance */}
          {trainee.marks && (
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Academic Performance</h3>
              <div className="bg-gray-50 p-6 rounded-lg">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                  <div className="text-center">
                    <p className="text-2xl font-bold text-blue-600">{trainee.totalMarks}</p>
                    <p className="text-sm text-gray-600">Total Marks (out of 1100)</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-green-600">
                      {((trainee.totalMarks || 0) / 1100 * 100).toFixed(2)}%
                    </p>
                    <p className="text-sm text-gray-600">Percentage</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-purple-600">{trainee.grade}</p>
                    <p className="text-sm text-gray-600">Grade</p>
                  </div>
                  <div className="text-center">
                    <p className={`text-2xl font-bold ${
                      ((trainee.totalMarks || 0) / 1100 * 100) >= 50 ? 'text-green-600' : 'text-red-600'
                    }`}>
                      {((trainee.totalMarks || 0) / 1100 * 100) >= 50 ? 'PASS' : 'FAIL'}
                    </p>
                    <p className="text-sm text-gray-600">Result</p>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <h4 className="font-medium text-gray-900 mb-3">Theory Subjects</h4>
                    <div className="space-y-2">
                      <div className="flex justify-between"><span>Railway Organization</span><span>{trainee.marks.railwayOrganization}/100</span></div>
                      <div className="flex justify-between"><span>Mechanical Dept Role</span><span>{trainee.marks.mechanicalDepartmentRole}/100</span></div>
                      <div className="flex justify-between"><span>Rolling Stock - Carriage</span><span>{trainee.marks.rollingStockCarriage}/100</span></div>
                      <div className="flex justify-between"><span>Rolling Stock - Wagon</span><span>{trainee.marks.rollingStockWagon}/100</span></div>
                      <div className="flex justify-between"><span>Rolling Stock - Diesel</span><span>{trainee.marks.rollingStockDiesel}/100</span></div>
                      <div className="flex justify-between"><span>Industrial Safety</span><span>{trainee.marks.industrialSafety}/100</span></div>
                    </div>
                  </div>
                  <div>
                    <h4 className="font-medium text-gray-900 mb-3">Practical Subjects</h4>
                    <div className="space-y-2">
                      <div className="flex justify-between"><span>Coach Production</span><span>{trainee.marks.coachProduction}/100</span></div>
                      <div className="flex justify-between"><span>RWF</span><span>{trainee.marks.rwf}/100</span></div>
                      <div className="flex justify-between"><span>DEMU/SPART</span><span>{trainee.marks.demuSpart}/100</span></div>
                      <div className="flex justify-between"><span>Diesel Production</span><span>{trainee.marks.dieselProduction}/100</span></div>
                      <div className="flex justify-between"><span>RDSO</span><span>{trainee.marks.rdso}/100</span></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Contact Information */}
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Contact Information</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <p className="text-sm font-medium text-gray-700">Address</p>
                <p className="text-gray-900">{trainee.address}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-700">Registration Date</p>
                <p className="text-gray-900">{new Date(trainee.createdAt).toLocaleDateString()}</p>
              </div>
            </div>
          </div>
        </div> {/* end of p-6 content */}
      </div>
    </div>
  );
}

          
      