import React, { useState } from 'react';
import * as html2pdf from 'html2pdf.js';
import { Download, CreditCard, User, Train, CheckCircle } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useData } from '../../context/DataContext';

export default function IDCard() {
  const { user } = useAuth();
  const { getTraineesByTrainer } = useData();
  const [selectedTrainee, setSelectedTrainee] = useState('');
  const [showSuccess, setShowSuccess] = useState(false);

  const myTrainees = getTraineesByTrainer(user?.trainerId || '');
  const selectedTraineeData = myTrainees.find(t => t.id === Number(selectedTrainee));


const generateIDCard = () => {
  if (!selectedTraineeData) return;

 const container = document.createElement('div');
container.innerHTML = `
  <div style="font-family: Times New Roman, Arial; margin: 0; padding: 0; height: 100vh; display: flex; justify-content: center; align-items: center;">
    <div style="width: 400px; border: 2px solid #003366; padding: 16px; border-radius: 10px; color: #003366; background-color: #f1f5f9; text-align: center;">
      <img src="/public/STC_logo.png" alt="STC Logo" style="max-width: 80px; height: auto; margin: 0 auto 12px; display: block;" />
      <div style="font-size: 18px; font-weight: bold; margin-bottom: 12px;">STC LUCKNOW | IDENTITY CARD</div>
      <div style="margin-bottom: 8px;"><strong>Name:</strong> ${selectedTraineeData.fullName}</div>
      <div style=" margin-bottom: 8px;"><strong>ID:</strong> ${selectedTraineeData.id}</div>
      <div style=" margin-bottom: 8px;"><strong>Course Duration:</strong> ${selectedTraineeData.courseDuration}</div>
      <div style=" margin-bottom: 8px;"><strong>Email:</strong> ${selectedTraineeData.email}</div>
      <div style=" margin-bottom: 8px;"><strong>Phone:</strong> ${selectedTraineeData.phoneNumber}</div>
      <div style=" margin-bottom: 8px;"><strong>Unit:</strong> ${selectedTraineeData.unit}</div>
      <div style=" margin-bottom: 8px;"><strong>Batch:</strong> ${selectedTraineeData.batch}</div>
      <div style="margin-top: 12px; font-size: 10px; color: #666;">Generated by STC Training System | ${new Date().toLocaleDateString()}</div>
    </div>
  </div>
`;

window.html2pdf()
  .set({
    margin: 0,
    filename: `id_card_${selectedTraineeData.id}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
  })
  .from(container)
  .save();


  setShowSuccess(true);
  setTimeout(() => setShowSuccess(false), 3000);
};


  return (
    <div className="space-y-6">
      {showSuccess && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <div className="flex items-center gap-2">
            <CheckCircle className="h-5 w-5 text-green-600" />
            <p className="text-green-800 font-medium">ID Card generated and downloaded successfully!</p>
          </div>
        </div>
      )}

      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Generate ID Card</h2>
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <select
              value={selectedTrainee}
              onChange={(e) => setSelectedTrainee(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select a trainee...</option>
              {myTrainees.map((trainee) => (
                <option key={trainee.id} value={trainee.id}>
                  {trainee.fullName} - {trainee.id}
                </option>
              ))}
            </select>
          </div>
          {selectedTraineeData && (
            <button
              onClick={generateIDCard}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
            >
              <Download className="h-4 w-4" />
              Generate ID Card
            </button>
          )}
        </div>
      </div>

      {selectedTraineeData && (
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">ID Card Preview</h3>
          <div className="id-card-preview border border-blue-800 rounded-lg p-4 text-blue-900 bg-blue-50 max-w-sm mx-auto text-center">
            <img src="/public/STC_logo.png" alt="STC Logo" className="max-w-[80px] h-auto mx-auto mb-2" />
            <p className="font-bold">STC LUCKNOW | IDENTITY CARD</p>
            <hr className="my-2" />
            <p><strong>Name:</strong> {selectedTraineeData.fullName}</p>
            <p><strong>ID:</strong> {selectedTraineeData.id}</p>
            <p><strong>Course Code:</strong> {selectedTraineeData.moduleNumber}</p>
            <p><strong>Course Duration:</strong> {selectedTraineeData.courseDuration}</p>
            <p><strong>Email:</strong> {selectedTraineeData.email}</p>
            <p><strong>Phone:</strong> {selectedTraineeData.phoneNumber}</p>
            <p><strong>Unit:</strong> {selectedTraineeData.unit}</p>
            <p><strong>Batch:</strong> {selectedTraineeData.batch}</p>
            <p className="text-xs text-center mt-4">Generated on: {new Date().toLocaleDateString()}</p>
          </div>
        </div>
      )}
    </div>
  );
}